include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  errors:
    public_member_api_docs: ignore
    inference_failure_on_function_invocation: ignore
  exclude:
    - build/**
linter:
  rules:
    file_names: false
